server:
  port: 8083
  error:
    include-message: always
    include-path: always
    include-binding-errors: always
spring:
  application:
    name: Mike's SSO app
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:mfa_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client_id
            client-secret: client_secret
            scope:
              - openid
              - profile
              - email

logging:
  level:
    ua.mike.sso: TRACE